# -*- coding: utf-8 -*-
"""DAY-2-python-and-machine-learning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7EdkEam_2M7Tg34dPA8dMfCRfgHhA-W
"""

from google.colab import files
uploaded = files.upload()

# ==========================================================
# STEP 1 - IMPORT LIBRARIES
# ==========================================================
import pandas as pd
import numpy as np

# ==========================================================
# STEP 2 - LOAD DATASET
# ==========================================================

df = pd.read_csv("Iris.csv")

print("FIRST FIVE RECORDS")
print(df.head())

print(df.info())

print(df.shape)

print(df.columns)

print(df.describe)

print(df.isnull().sum())

print(df.duplicated().sum())

print(df["Species"].unique())

print(df.tail())